### ISSUE TITLE
Crawling of all sites during build

### ISSUE THREAD

**Issue by kleinicke** [sbsev/svelte-site#19]
Currently not all pages are build, since there are only links from the nav to these pages.

A crawler which finds all pages need to be readded.

**Comment by kleinicke** [comment]
And when content is added on Contentful, the site should be either rebuild, or the content should be used dynamically on the website.

**Comment by janosh** [comment]
> A crawler which finds all pages need to be readded.

readded? We never wrote a crawler in the first place.

> And when content is added on Contentful, the site should be either rebuild, or the content should be used dynamically on the website.

This should be in a separate issue. And it's easy to fix, either we revert to `load()` functions instead of shadow endpoints or we reactivate the Contentful to Netlify webhook.

**Comment by kleinicke** [comment]
Here you disabled, that the pages will be prebuilt right?
https://github.com/sbsev/svelte-site/commit/22b429406c1a8e285702b166d2123970e6671c69#diff-6317e218ea40a2a9b47af98e100e81c06f9c0abff66737e6ca06ec4b29402242

**Comment by janosh** [comment]
Correct. Though rather than reinstating that it would be better to find out why the crawler does not follow nav links. I suspect it's due to them not being rendered unless user hovers over them which of course doesn't happen during SSR. So we should check for [`env.prerendering`](https://kit.svelte.dev/docs/modules#$app-env)

```ts
import { prerendering } from '$app/env'
```

in `Nav.svelte` and render all `subNavs` if `true`.
