### ISSUE TITLE
Menu bar overlaps image

### ISSUE THREAD

**Issue by alchemiker** [sbsev/svelte-site#4]
Here I am again : )
Most pages (or even all?) start with a picture on the top, which is overdrawn a bit by the dark blue menu bar at the top of the webpage.
Since most pictures are just symbol images, it is not so noticeable, but at the Page [Bundesvorstand](https://studenten-bilden-schueler.de/bundesvorstand/) for example the heads of the people in the top row are cut off.

P.S.: if I comment in the wrong place tell me where to report bugs instead.

**Comment by janosh** [comment]
Hi @alchemiker! Thanks again for reaching out. It's really the menu bar at fault here. Just that the hero images are told to take up a max height of `50vh`. For some images like the one on the BV page you linked, that means on some screens they will have to be cropped vertically. Since I'm reluctant to let hero images display at their natural aspect ratio in order to prevent any from extending beyond the fold, a good compromise might be to just increase the max height to, say, `65vh`? Will be part of the next commit.

**Comment by alchemiker** [comment]
Hello @janosh, thank you very much for the explanation!
Such things as how to keep pictures at a reasonable size across different devices are what a typical internet user never thinks about... As a noob I would only restrict the horizontal size, but yeah, at certain devices it would cover the whole page and make it obvious that my site were made by a noob ; )

But maybe it could be also an idea to crop the images (or only at pages, which have people in the hero image) from the bottom and not from the top?

In the attachments you can see a screenshot of the page how it is seen on my laptop (Lenovo X201, Windows 8.1, in Mozilla Firefox) so you can estimate the value for max height which is required to avoid such a cropping.

![grafik](https://user-images.githubusercontent.com/63516327/113913910-2e94c380-97dd-11eb-8472-de0b47891b6e.png)

**Comment by janosh** [comment]
> But maybe it could be also an idea to crop the images (or only at pages, which have people in the hero image) from the bottom and not from the top?

It's actually from the bottom _and_ the top so that the image remains centered. That usually works best in the majority of cases. Not so much for this image, I agree.

> In the attachments you can see a screenshot of the page how it is seen on my laptop (Lenovo X201, Windows 8.1, in Mozilla Firefox) so you can estimate the value for max height which is required to avoid such a cropping.
I cropped it this morning. Should be slightly better next time the site is built. Together with the increased height allowance, hopefully no more cropped heads. :)

**Comment by janosh** [comment]
I'll go ahead and close this but feel free to open new issues if you encounter more on our site! Thanks for letting us know each time!
