### ISSUE TITLE
Show longer names in one line under pictures on the website (eg Bundesvorstand)

### ISSUE THREAD

**Issue by JanaNF** [sbsev/svelte-site#55]
Names like Jana Nina Friedrich, Christop Bischoff, etc are too long for one line and this is why the name is in two lines. This is ugly. Would be nice to show the full name in one line.

**Comment by dominikgeissler** [comment]
Since we can't just remove a part of the name, I'ld suggest a separation of the name and the area (they are currently stored into one paragraph).
If I understood Christoff correctly, he wanted the areas to be on the same height (even with a long name). We could use dedicated divs with fixed space for name and area for example.

**Comment by dominikgeissler** [comment]
See #43.
